name: Panawave
favicon: null
layout_spectrum: 0.4059095911215991
typography_spectrum: 0.36127
title: Panawave
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdf8e5'
    - '#7d7e78'
    - '#dbcba9'
    - '#244161'
    - '#2a648a'
  brandStrength: 0.8858135628979653
  lightness: 0.30915492703206837
  saturation: 0.21823594742454588
  rhythmicContrast: 0.8249460032675415
purpose: []
